name: loyaltyapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0-0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7+1
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  flutter_animate: ^4.5.2
  flutter_colorpicker: ^1.1.0
  flutter_image_slideshow: ^0.1.6
  flutter_map: ^7.0.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  geocoding: ^2.2.2
  geolocator: ^9.0.2
  go_router: ^13.2.5
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  logger: ^2.5.0
  lottie: ^3.2.0
  lucide_icons: ^0.257.0
  mobile_scanner: ^3.5.7
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  sensors_plus: ^4.0.2
  share_plus: ^10.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sign_in_button: ^3.2.0
  url_launcher: ^6.3.1
  vector_math: ^2.1.4
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/categories/check.json
